# Application mode: 'test' or 'production'
app_mode: debug

# Logging configuration
logging:
  level: DEBUG
  file: app.log

# Default Base URL to Cloudfront
cloudfront_base_url: https://d2vr5rnk314mjb.cloudfront.net/
s3_subfolder: obsidian_attachments/
s3_bucket_name: gbacbucket

# UI configuration
ui:
  font:
    family: Calibri
    size: 10
  theme:
    dark:
      # Main colors
      background: "#1E1E1E"
      text: "#FFFFFF"
      accent: "#007ACC"

      # Table colors
      table:
        header: "#2D2D2D"
        background: "#252526"
        alternate_row: "#2D2D2D"
        grid: "#3C3C3C"

      search:
        background: "#2D2D2D"
        border: "#3C3C3C"
        focus: "#4CAF50"

      # Button colors (updated)
      button:
        background: "#3C3C3C"
        text: "#FFFFFF"
        hover: "#505050"
        disabled:
          background: "#2A2A2A"
          text: "#808080"

      # Input field colors
      input:
        background: "#3C3C3C"
        text: "#FFFFFF"
        border: "#555555"

      # Splitter color
      splitter: "#2D2D2D"

      # Title bar colors
      titlebar:
        background: "#2D2D2D"
        text: "#FFFFFF"
        button_hover: "#3C3C3C"

      # Scrollbar colors
      scrollbar:
        background: "#1E1E1E"
        handle: "#3C3C3C"
        border: "#2D2D2D"
        button: "#3C3C3C"
        arrow: "#555555"

      border_radius:
        button: 5px
        input: 5px

vault_directory: D:/projects/vaultmanager/test-vault
